baseURL               = "https://topai.cool/"
languageCode          = "zh-CN"
title                 = "Topai.cool | AI工具集导航 | 500+ AI工具导航大全，国内外AI工具集合网站"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "Topai.cool"
    keywords      = "AI工具集,AI工具集官网,AI工具集网站,AI工具集导航,AI工具集导航官网,AI工具导航,AI工具大全,AI网站大全,AI软件大全,AI工具集合,AI工具集合网,AI工具库,AI工具箱,AI工具箱导航"
    description   = "AI工具集导航收录了国内外数百个AI工具，包括AI写作工具、AI图像生成和背景移除、AI视频制作、AI音频转录、AI辅助编程、AI音乐生成、AI绘画设计、AI对话聊天等AI工具集合大全，以及AI学习开发的常用网站、框架和模型，帮助你加入人工智能浪潮，自动化高效完成任务！"
    upload        = "https://www.yuque.com/forms/share/1a1fee15-f7a9-4ee6-9dd4-b0ba9fef1871"  # 左侧导航栏的"网站提交"
    about         = "#"	# 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = false					# 网站完全打开前预加载动画
    textPreLoad   = "AI工具集导航"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    logosHttpPath = "https://api.iowen.cn/favicon"			# 网站每个导航地址logo存放地址


    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = false                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = 'cf9e9fd77f22a77aac6deb2e4e28f17a'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-NlqCJPuVTy'			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
#    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/blur-shape.png"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：topai.cool#proton.me <br/>Copyright © {year} By topai.cool<br/>'
